return {
	--     {
	--         -- Highlights all instances of the visual selection
	--         "wurli/visimatch.nvim",
	--         opts = {}
	--     },
	--     {
	--         -- Highlights all instances of the word under the cursor
	--         "RRethy/vim-illuminate",
	--         opts = {
	--             providers = {
	--                 'regex',
	--                 'treesitter',
	--                 'lsp',
	--             },
	--             delay = 200,
	--             large_file_cutoff = 2000,
	--             large_file_overrides = {
	--                 providers = { "lsp" },
	--             },
	--         },
	--         config = function(_, opts)
	--             require('illuminate').configure(opts)
	--         end,
	--     },
}
